# cmd conda build . -c
package:
    name: nst
    version: "1.0.0"

source:
    path: .

requirements:
    build:
        - cmake
        - blas
        - openblas # [linux]
    run:
        - cmake
        - blas
        - openblas # [linux]
